import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

const PRESIGNED_URL_TTL_SECONDS = 5 * 60;

// This intentionally accepts only SemVer releases. The normalized form is used
// exclusively to construct release keys; neither route parameter is an S3 key.
const RELEASE_VERSION = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-(?:0|[1-9]\d*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))*)?$/;

const METADATA_FILES = new Set([
  "release-manifest.json",
  "release-manifest.json.asc",
]);

function requiredEnvironment(name: string) {
  const value = process.env[name];
  if (!value) throw new Error(`${name} environment variable is required`);
  return value;
}

let s3Client: S3Client | undefined;

function getS3Client() {
  s3Client ??= new S3Client({ region: requiredEnvironment("AWS_REGION") });
  return s3Client;
}

export function normalizeReleaseVersion(value: string) {
  const version = value.startsWith("v") ? value.slice(1) : value;
  return RELEASE_VERSION.test(version) ? version : null;
}

export function isAllowedReleaseFilename(version: string, filename: string) {
  if (METADATA_FILES.has(filename)) return true;

  // These are the only five files generated by scripts/build-release.sh.
  return new Set([
    `owlcode_${version}_linux_x64.tar.gz`,
    `owlcode_${version}_linux_arm64.tar.gz`,
    `owlcode_${version}_windows_x64.zip`,
    `owlcode_${version}_macos_x64.tar.gz`,
    `owlcode_${version}_macos_arm64.tar.gz`,
  ]).has(filename);
}

export function releaseObjectKey(version: string, filename: string) {
  return `releases/v${version}/${filename}`;
}

export async function createReleaseDownloadUrl(version: string, filename: string) {
  const bucket = requiredEnvironment("S3_BUCKET");
  return getSignedUrl(
    getS3Client(),
    new GetObjectCommand({ Bucket: bucket, Key: releaseObjectKey(version, filename) }),
    { expiresIn: PRESIGNED_URL_TTL_SECONDS },
  );
}

export async function createSigningKeyDownloadUrl() {
  const bucket = requiredEnvironment("S3_BUCKET");
  return getSignedUrl(
    getS3Client(),
    new GetObjectCommand({ Bucket: bucket, Key: "owlcode-signing-key.asc" }),
    { expiresIn: PRESIGNED_URL_TTL_SECONDS },
  );
}
